"""P1 - cryptographic provenance (C2PA), Sec.4 L1 stage 1.

Reads any C2PA manifest embedded in the image and reports what it says
about how the image was produced.

**Absent provenance is UNKNOWN, never adverse.** This is the single most
important thing about this pillar, and it is a product decision rather
than a technical one. Practically no consumer photo in India carries
C2PA: WhatsApp - the dominant channel for sending a merchant a damage
photo - strips it, as do most social platforms and messaging apps. A
system that treated "no manifest" as evidence of fraud would deny
essentially every honest claim. So `UNKNOWN` is the expected state, it
carries no risk weight of its own, and `SAFETY.md` commits to that in
public.

The pillar therefore only ever contributes *positively identifying*
evidence: a valid manifest saying "captured by a camera" is mild support
for authenticity; a valid manifest saying "generated by an AI tool" is
strong evidence against. Neither is common, and that is fine - a pillar
that fires rarely but is nearly always right when it does is worth
having, provided nothing downstream mistakes its silence for a verdict.

`c2pa-python` is an optional dependency (`pip install
'pramaan[provenance]'`). Without it, every claim reports UNKNOWN with
`library_available=False`, which is a legitimate deployment state and
not an error.
"""

from __future__ import annotations

import io
import json
import logging
from dataclasses import dataclass
from enum import Enum
from functools import lru_cache

logger = logging.getLogger(__name__)


class ProvenanceStatus(str, Enum):
    """What the image's C2PA manifest (if any) establishes."""

    UNKNOWN = "UNKNOWN"  # no manifest, or no library - the common case
    VALID_CAMERA = "VALID_CAMERA"  # signed capture by a hardware device
    VALID_EDITED = "VALID_EDITED"  # signed, with editing actions recorded
    VALID_AI_GENERATED = "VALID_AI_GENERATED"  # manifest declares synthesis
    INVALID = "INVALID"  # manifest present but fails validation


# Assertion labels / action names that indicate synthesis. C2PA's
# `c2pa.actions` vocabulary marks AI generation explicitly, which is the
# whole reason this pillar can be decisive when a manifest exists.
_AI_ACTION_MARKERS = (
    "c2pa.created",
    "digitalsourcetype/trainedalgorithmicmedia",
    "digitalsourcetype/compositewithtrainedalgorithmicmedia",
)
_AI_KEYWORDS = ("trainedalgorithmicmedia", "generativeai", "ai_generated")
_CAMERA_MARKERS = ("c2pa.captured", "digitalsourcetype/digitalcapture")
_EDIT_MARKERS = ("c2pa.edited", "c2pa.cropped", "c2pa.filtered", "c2pa.placed")


@dataclass
class ProvenanceFeatures:
    """P1's contribution to the fused feature vector.

    Note there is no "provenance_absent_is_bad" style feature. The
    booleans below are all *positive* assertions - each is False when
    nothing is known, so a missing manifest contributes nothing in either
    direction rather than contributing risk.
    """

    status: ProvenanceStatus = ProvenanceStatus.UNKNOWN
    library_available: bool = True
    has_manifest: bool = False
    manifest_valid: bool = False
    declares_ai_generation: bool = False
    declares_camera_capture: bool = False
    declares_editing: bool = False
    n_assertions: int = 0
    validation_error: str | None = None

    def as_dict(self) -> dict[str, float]:
        return {
            "provenance_has_manifest": float(self.has_manifest),
            "provenance_manifest_valid": float(self.manifest_valid),
            "provenance_declares_ai_generation": float(self.declares_ai_generation),
            "provenance_declares_camera_capture": float(self.declares_camera_capture),
            "provenance_declares_editing": float(self.declares_editing),
            "provenance_n_assertions": float(self.n_assertions),
        }


@lru_cache(maxsize=1)
def c2pa_available() -> bool:
    try:
        import c2pa  # noqa: F401
    except Exception as exc:  # noqa: BLE001 - a broken native wheel is also "unavailable"
        logger.info("c2pa unavailable (%s); provenance will report UNKNOWN", type(exc).__name__)
        return False
    return True


def _classify(manifest_json: str) -> ProvenanceFeatures:
    features = ProvenanceFeatures(has_manifest=True, manifest_valid=True)
    try:
        data = json.loads(manifest_json)
    except json.JSONDecodeError as exc:
        return ProvenanceFeatures(
            status=ProvenanceStatus.INVALID,
            has_manifest=True,
            manifest_valid=False,
            validation_error=f"unparseable manifest: {exc}",
        )

    blob = json.dumps(data).lower()

    manifests = data.get("manifests", {})
    active = data.get("active_manifest")
    active_manifest = manifests.get(active, {}) if active else {}
    assertions = active_manifest.get("assertions", [])
    features.n_assertions = len(assertions)

    features.declares_ai_generation = any(m in blob for m in _AI_KEYWORDS) or any(
        m in blob for m in _AI_ACTION_MARKERS if "trainedalgorithmic" in m
    )
    features.declares_camera_capture = any(m in blob for m in _CAMERA_MARKERS)
    features.declares_editing = any(m in blob for m in _EDIT_MARKERS)

    if features.declares_ai_generation:
        features.status = ProvenanceStatus.VALID_AI_GENERATED
    elif features.declares_editing:
        features.status = ProvenanceStatus.VALID_EDITED
    elif features.declares_camera_capture:
        features.status = ProvenanceStatus.VALID_CAMERA
    else:
        # A signed manifest that asserts nothing we recognise. Valid, but
        # it establishes nothing about how the image was made.
        features.status = ProvenanceStatus.UNKNOWN
    return features


def extract_provenance(raw_bytes: bytes) -> ProvenanceFeatures:
    """Reads C2PA provenance. Never raises: an unreadable or absent
    manifest is UNKNOWN, which is the expected state for the overwhelming
    majority of real claim images."""
    if not c2pa_available():
        return ProvenanceFeatures(status=ProvenanceStatus.UNKNOWN, library_available=False)

    import c2pa

    try:
        # `stream`, not raw bytes: passing bytes directly raises an
        # AttributeError deep in the native layer, which an error handler
        # that classifies by message would misread as a *failed manifest*
        # on every ordinary image.
        reader = c2pa.Reader("image/jpeg", io.BytesIO(raw_bytes))
        manifest_json = reader.json()
    except Exception as exc:  # noqa: BLE001 - c2pa raises varied native errors
        # Distinguish "no manifest" from "manifest failed validation" by
        # exception TYPE rather than by string-matching the message.
        # c2pa raises ManifestNotFound for the ordinary case, and message
        # wording is not part of any stable contract.
        if type(exc).__name__ == "ManifestNotFound":
            return ProvenanceFeatures(status=ProvenanceStatus.UNKNOWN)
        return ProvenanceFeatures(
            status=ProvenanceStatus.INVALID,
            has_manifest=True,
            manifest_valid=False,
            validation_error=f"{type(exc).__name__}: {exc}"[:200],
        )

    if not manifest_json:
        return ProvenanceFeatures(status=ProvenanceStatus.UNKNOWN)
    return _classify(manifest_json)
